# Generated by Django 2.2.6 on 2019-10-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20191013_0430'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='occurring',
        ),
        migrations.RemoveField(
            model_name='event',
            name='hidden',
        ),
        migrations.AddField(
            model_name='event',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
