# Generated by Django 2.2.6 on 2019-10-13 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20191013_0434'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='occurring',
            new_name='start',
        ),
        migrations.AddField(
            model_name='event',
            name='duration',
            field=models.PositiveSmallIntegerField(default=23),
            preserve_default=False,
        ),
    ]
