# Generated by Django 2.2.6 on 2019-11-24 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20191013_0612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='start',
            new_name='cron',
        ),
    ]
