# Generated by Django 2.2.6 on 2019-12-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20191124_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='img',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
