# Generated by Django 2.2.6 on 2019-12-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_event_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='url',
            field=models.URLField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
