# Generated by Django 2.1.3 on 2018-11-18 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account_details', '0002_auto_20181118_0626'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='bio',
            field=models.TextField(default=''),
        ),
    ]
