# Generated by Django 2.1.3 on 2018-12-09 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181209_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(help_text='Comma seperated, e.g. (javascript django )', to='blog.Tag'),
        ),
    ]
