# Generated by Django 2.1.3 on 2019-01-06 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190105_0839'),
        ('blog', '0011_article_user'),
    ]

    operations = [
    ]
